<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SwitchOnYourCode/SwitchOnYourCode.csproj" />
    <ProjectReference Include="../../src/SwitchOnYourCode.OpenFeature/SwitchOnYourCode.OpenFeature.csproj" />
    <ProjectReference Include="../../src/SwitchOnYourCode.Extensions.DependencyInjection/SwitchOnYourCode.Extensions.DependencyInjection.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="OpenFeature" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
